# docker/docker-compose.yml
version: '3.4'

services:
  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3307:3306"
    volumes:
      - ./docker/database/data:/var/lib/mysql

  php-fpm:
    build:
      context: ./docker/php-fpm
      target: php_base
    depends_on:
      - database
    volumes:
      - .:/var/www

  php-fpm-with-xdebug:
    build:
      context: ./docker/php-fpm
      target: php_test
    depends_on:
      - database
      - php-fpm
    volumes:
      - .:/var/www

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
      - php-fpm-with-xdebug
    ports:
      - "8000:80"
      - "8001:81"
